title: "Computational Physics"
description: "A GitHub Pages site using remote theme"
baseurl: "" 
url: "https://baileygrollo.github.io"

plugins:
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-sitemap

remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

header:
  nav: main
  
author:
  name: "Bailey Grollo"
  avatar: "/assets/img/ascii-animation.gif"
  bio: "Quantum Physicist at [RMIT University](https://www.rmit.edu.au)"
  location: "Melbourne, Australia"
  github: baileygrollo
  linkedin: baileygrollo 
  
include:
  - _pages
